### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by tintsch** [loriot/miotyGO#4]
Hardware: Raspberry Pi 4, SDRPlay RSP1A
Software: SDRPlay aarch64, SDRPlay API installed
Getting an error for an unmet dependency 'libRspTransceiverDevice-0.8.so',
can you provide a source for this library?

Installer output:
```
pi@miotygo:~ $ sudo ./miotyGO_install_aarch64.sh
> Extracting Mioty files ...
>>> Found payload, checking integrity ... done
>>> Extracting to /opt/miotyGO...  done
> Checking requirements ... libRspTransceiverDevice-0.8.so not found>>>>> ERROR: Install dependencies failed with code: 1
```

**Comment by aectaan** [comment]
@tintsch try previous release - installed ok for x86

**Comment by lorryOT** [comment]
Hi all,

Fix is already done and in the next hours will be released as a new version, at the moment, you can find the fix in [this branch](https://github.com/loriot/miotyGO/tree/5-dependency-error)

Thank you,

Loriot Team.

**Comment by aectaan** [comment]
Looks like fix is not tested properly. Fresh install gives another missed package. Solution is the same: install v1.0 and after that switch to v1.2 tag
```
sudo ./miotyGO_install.sh 
 _      ____  _____  _____ ____ _______ 
| |    / __ \|  __ \|_   _/ __ \__   __|
| |   | |  | | |__) | | || |  | | | |   
| |   | |  | |  _  /  | || |  | | | |   
| |___| |__| | | \ \ _| || |__| | | |   
|______\____/|_|  \_\_____\____/  |_|   
                                        
                                        
> Extracting Mioty files ... 
>>> Found payload, checking integrity ... done
>>> Extracting to /opt/miotyGO...  done
> Checking requirements ... ... libmirsdrapi-rsp.so not found>>>>> ERROR: Install dependencies failed with code: 1
```

**Comment by lorryOT** [comment]
Apologies for the misunderstanding, now there is updated with the correct version of the installer for both platforms.

Please check again and let us know the result of the testing, installer should be working with any issues.

Thank you for your time.
