### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by aectaan** [loriot/miotyGO#5]
Hi there. Trying to install software to x86, getting this kind of error: 
```                                  
> Extracting Mioty files ... 
>>> Found payload, checking integrity ... done
>>> Extracting to /opt/miotyGO...  done
> Checking requirements ... libRspTransceiverDevice-0.8.so not found>>>>> ERROR: Install dependencies failed with code: 1
```

Which packet is missing? Thank you.

**Comment by lorryOT** [comment]
Hi, 

We found there is a missing dependency on this version, we manage to solve it and the solution should be available really soon as a new release.

At the moment please try with [this branch](https://github.com/loriot/miotyGO/tree/5-dependency-error)

Thank you,

Loriot team.
